/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Gamberro
 */
public class Ventasycompras extends javax.swing.JFrame {

    /**
     * Creates new form ventasycompras
     */
    public Ventasycompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nada = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtclave = new javax.swing.JPasswordField();
        inicio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        nada.setBackground(new java.awt.Color(0, 0, 0));
        nada.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        nada.setForeground(new java.awt.Color(0, 0, 0));
        nada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nada.setText("Iniciar secion ");
        getContentPane().add(nada);
        nada.setBounds(-30, 80, 400, 25);

        usuario.setFont(new java.awt.Font("DialogInput", 1, 11)); // NOI18N
        usuario.setForeground(new java.awt.Color(0, 0, 0));
        usuario.setText("Usuario");
        getContentPane().add(usuario);
        usuario.setBounds(0, 120, 60, 16);

        contraseña.setFont(new java.awt.Font("DialogInput", 1, 11)); // NOI18N
        contraseña.setForeground(new java.awt.Color(0, 0, 0));
        contraseña.setText("Contraseña");
        getContentPane().add(contraseña);
        contraseña.setBounds(200, 120, 70, 16);

        txtusuario.setBackground(new java.awt.Color(0, 0, 0));
        txtusuario.setForeground(new java.awt.Color(204, 204, 255));
        txtusuario.setDisabledTextColor(new java.awt.Color(255, 204, 255));
        txtusuario.setSelectionColor(new java.awt.Color(204, 204, 255));
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtusuario);
        txtusuario.setBounds(10, 150, 130, 30);

        txtclave.setBackground(new java.awt.Color(0, 0, 0));
        txtclave.setForeground(new java.awt.Color(204, 204, 255));
        txtclave.setCaretColor(new java.awt.Color(255, 204, 204));
        txtclave.setDisabledTextColor(new java.awt.Color(255, 204, 204));
        txtclave.setSelectionColor(new java.awt.Color(255, 204, 255));
        txtclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclaveActionPerformed(evt);
            }
        });
        getContentPane().add(txtclave);
        txtclave.setBounds(210, 150, 130, 30);

        inicio.setBackground(new java.awt.Color(0, 0, 0));
        inicio.setFont(new java.awt.Font("DialogInput", 1, 11)); // NOI18N
        inicio.setText("Iniciar secion");
        inicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        getContentPane().add(inicio);
        inicio.setBounds(210, 240, 150, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/anonymous-black-octobersi.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -10, 1310, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclaveActionPerformed

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        String nombre = "luisda";
        String pasword = "daniel103195";
        String clave = new String(txtclave.getPassword());
        Principal pantalla2 = new Principal();
        if (txtusuario.getText().equals(nombre) && clave.equals(pasword)) {
            JOptionPane.showMessageDialog(this, "correcto", null, JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/fotos/si.png"));
            pantalla2.setVisible(rootPaneCheckingEnabled);
        } else {
            JOptionPane.showMessageDialog(this, "incorrecto", null, JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/fotos/no.png"));
        }
    }//GEN-LAST:event_inicioActionPerformed

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventasycompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventasycompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventasycompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventasycompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventasycompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contraseña;
    private javax.swing.JButton inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nada;
    private javax.swing.JPasswordField txtclave;
    private javax.swing.JTextField txtusuario;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
